POST {{host}}/user/signup
Content-Type: application/json

{
  "name": "nguyen",
  "email": "nguyen2@gmail.com",
  "password": "12345678"
}
###
POST {{host}}/user/signin
Content-Type: application/json

{
    "email": "truong3@gmail.com",
    "password": "123"
}
###
GET {{host}}/user/1
#Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJpYXQiOjE3MzI2NzkwMjAsImV4cCI6MTczMjc2NTQyMCwiZW1haWwiOiJ0cnVvbmczQGdtYWlsLmNvbSIsImF1dGhvcml0aWVzIjoiUk9MRV9BRE1JTiJ9.hXb2LMVupbSkPAV9K9xkLiVpPI4MkuCnKpkbOu6Y5lMk1tzMhhRncni44XvkN_J9